# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=200, unique=True)),
                ('date_of_creation', models.DateField(auto_now_add=True, db_index=True)),
                ('Last_Modified', models.DateField(auto_now_add=True, db_index=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, unique=True)),
                ('blog_slug', models.CharField(max_length=200, unique=True)),
                ('creation_timestamp', models.DateField(auto_now_add=True, db_index=True)),
                ('modified_timestamp', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog_part',
            name='blogID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_Table'),
        ),
    ]
