# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_now_add=True, db_index=True)),
                ('Last_Modified', models.DateField(auto_now_add=True, db_index=True)),
                ('Content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_table',
            name='blog_body',
        ),
        migrations.AddField(
            model_name='blog_part',
            name='blogID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_Table'),
        ),
    ]
