# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171122_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_part',
            name='part_title',
            field=models.CharField(default='none', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_part',
            name='slug',
            field=models.CharField(default='none', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
