# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_table_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_part',
            name='blogID',
        ),
    ]
