# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_part_blogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_part',
            name='blogID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_Table'),
        ),
    ]
